name: Tests
on: push

jobs:
  test:
    name: Bun Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3
      - name: Setup Bun
        uses: oven-sh/setup-bun@1
      
      - name: Install Dependencies
        run: bun install

      - name: Run Tests
        run: bun test